---
- name: Echo to sysctl.conf on {{ ansible_hostname }}
  command: "echo {{ item }} >> /etc/sysctl.conf"
  with_items:
  - net.ipv4.conf.all.forwarding=1
  - net.ipv4.ip_forward=1

- name: Add route and rule in inetRouter
  command: "{{ item }}"
  with_items:
  - echo '192.168.0.0/16 via 192.168.255.2 dev bond0' >> /etc/sysconfig/network-scripts/route-bond0
  - iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
  when: ansible_hostname == "inetRouter"

- name:	Add routes in centralRouter
  command: "{{ item }}"
  with_items:
  - echo 'DEFROUTE=no' >> /etc/sysconfig/network-scripts/ifcfg-eth0 
  - echo '192.168.2.0/24 via 192.168.254.2 dev bond0:0' >> /etc/sysconfig/network-scripts/route-bond0
  - echo '192.168.3.0/24 via 192.168.254.2 dev bond0:0' >> /etc/sysconfig/network-scripts/route-bond0
  - echo '192.168.1.0/24 via 192.168.253.2 dev bond0:1' >> /etc/sysconfig/network-scripts/route-bond0
  when:	ansible_hostname == "centralRouter"

- name: Restart network
  service:
    name: network
    state: restarted
